objects/Progress_Bar_Question__c.object
<CustomObject>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <inlineHelpText>This field will have the name of the field to which the question is related.</inlineHelpText>
        <label>Field Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <inlineHelpText>This field will have the name of the object to which the question is related.</inlineHelpText>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <inlineHelpText>The question will display for progress bar.</inlineHelpText>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weightage__c</fullName>
        <inlineHelpText>This field determines the weightage of question.</inlineHelpText>
        <label>Weightage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Progress Bar Question</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Bar Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSumofWeightage.cls
@isTest public class TestSumofWeightage {
    @isTest public static void testinsertWeightage(){
        Decimal sum=0;
        Progress_Bar_Question__c p = new Progress_Bar_Question__c();
        p.Field_Api_Name__c = 'Email';
        p.Object_Name__c = 'Contact';
        p.Question__c = 'Enter Email';
        p.Weightage__c = 120;
        Database.SaveResult result = Database.insert(p, false);
        List<Progress_Bar_Question__c> pb=[select id,Weightage__c from Progress_Bar_Question__c LIMIT 50000];
        for(Progress_Bar_Question__c prog:pb){
            sum=sum+prog.Weightage__c;
        }
        if(sum > 100){
            System.assertEquals('The total sum of weightage of all questions should not be greater than 100.',result.getErrors()[0].getMessage());
        }
    }
    @isTest public static void testUpdateWeightage(){
        Decimal sum=0;
        Progress_Bar_Question__c p = new Progress_Bar_Question__c();
        p.Field_Api_Name__c = 'Email';
        p.Object_Name__c = 'Contact';
        p.Question__c = 'Enter Email';
        p.Weightage__c = 70;
        Database.SaveResult insertResult = Database.insert(p, false);
        p.Weightage__c=40;
        Database.SaveResult updateResult = Database.update(p, false);
        List<Progress_Bar_Question__c> pb=[select id,Weightage__c from Progress_Bar_Question__c LIMIT 50000];
        for(Progress_Bar_Question__c prog:pb){
            sum=sum+prog.Weightage__c;
        }
        if(sum > 100){
            System.assertEquals('The total sum of weightage of all questions should not be greater than 100.',updateResult.getErrors()[0].getMessage());
        }
    }
}